# Generated by Django 2.2 on 2019-05-09 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('image_url', models.ImageField(upload_to='media/newsroom')),
                ('events', models.TextField(max_length=500)),
                ('location', models.IntegerField(choices=[(1, 'Hiphop'), (2, 'Trap'), (3, 'Gospel'), (4, 'THIKA'), (5, 'NGONG'), (6, 'EASTLEIGH'), (7, 'KIKUYU'), (8, 'UTHIRU'), (9, 'ALL')], default=9)),
            ],
        ),
    ]
