# Generated by Django 2.2 on 2019-05-09 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsRoom', '0003_auto_20190509_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsroom',
            name='image_url',
            field=models.ImageField(upload_to='Media/newsroom'),
        ),
    ]
