# Generated by Django 2.2 on 2019-05-09 11:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('image_url', models.ImageField(upload_to='images/music')),
                ('artist', models.CharField(max_length=140)),
                ('album', models.CharField(max_length=140)),
                ('slug', models.SlugField(unique=True)),
                ('genre', models.IntegerField(choices=[(1, 'Hiphop'), (2, 'Trap'), (3, 'Gospel'), (4, 'Bongo'), (5, 'Soul'), (6, 'No Category')], default=6)),
                ('play', models.TimeField()),
                ('music_file', models.FileField(blank=True, help_text='.mp3,.wav,.ogg Audio files Allowed', upload_to='media/audios', validators=[django.core.validators.FileExtensionValidator(['.mp3', '.wav', '.ogg'])])),
            ],
        ),
    ]
