# Generated by Django 2.2 on 2019-05-09 12:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='music_file',
            field=models.FileField(blank=True, help_text='.mp3,.wav,.ogg Audio files Allowed', upload_to='media/audios', validators=[django.core.validators.FileExtensionValidator(['mp3', 'wav', 'ogg'])]),
        ),
    ]
