# Generated by Django 2.2 on 2019-05-02 07:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GifAdverts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('ad_priority', models.PositiveIntegerField(choices=[(1, 'Most Priority'), (2, 'Average Priority'), (3, 'Least Priority')], default=3)),
                ('gif_url', models.FileField(help_text='Gif Files only allowed', null=True, upload_to='media/adverts/gif', validators=[django.core.validators.FileExtensionValidator(['gif'])])),
            ],
        ),
        migrations.CreateModel(
            name='ImageAdverts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('ad_priority', models.PositiveIntegerField(choices=[(1, 'Most Priority'), (2, 'Average Priority'), (3, 'Least Priority')], default=3)),
                ('advert_image', models.ImageField(blank=True, help_text='Jpg image files allowed', upload_to='media/adverts/images', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])])),
            ],
        ),
        migrations.CreateModel(
            name='VideosAdverts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('ad_priority', models.PositiveIntegerField(choices=[(1, 'Most Priority'), (2, 'Average Priority'), (3, 'Least Priority')], default=3)),
                ('video_url', models.FileField(help_text='Only Video Files Allowed', null=True, upload_to='media/adverts/videos', validators=[django.core.validators.FileExtensionValidator(['mp4', '3gp', 'flv', 'mkv'])])),
            ],
        ),
    ]
