# Generated by Django 2.2 on 2019-05-09 13:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adverts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gifadverts',
            name='gif_url',
            field=models.FileField(help_text='Gif Files only allowed', null=True, upload_to='Media/adverts/gif', validators=[django.core.validators.FileExtensionValidator(['gif'])]),
        ),
        migrations.AlterField(
            model_name='imageadverts',
            name='advert_image',
            field=models.ImageField(blank=True, help_text='Jpg image files allowed', upload_to='Media/adverts/images', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='videosadverts',
            name='video_url',
            field=models.FileField(help_text='Only Video Files Allowed', null=True, upload_to='Media/adverts/videos', validators=[django.core.validators.FileExtensionValidator(['mp4', '3gp', 'flv', 'mkv'])]),
        ),
    ]
