# Generated by Django 2.2 on 2019-05-09 11:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.ImageField(blank=True, upload_to='images/movies')),
                ('title', models.CharField(max_length=140)),
                ('category', models.IntegerField(default=1)),
                ('movie_url', models.FileField(blank=True, help_text='MP4,MKV,3GP Files allowed', upload_to='media/movies', validators=[django.core.validators.FileExtensionValidator(['mp4', 'mkv', 'flv'])])),
                ('star_ratings', models.PositiveIntegerField(default=3)),
                ('plot', models.TextField()),
                ('year', models.PositiveIntegerField(default=2018)),
                ('rating', models.PositiveIntegerField(default=1)),
                ('runtime', models.PositiveIntegerField(default=0)),
                ('slug', models.SlugField(unique=True)),
                ('website', models.URLField(blank=True)),
                ('views', models.PositiveIntegerField(default=100)),
            ],
        ),
    ]
