# Generated by Django 2.2 on 2019-05-09 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='image_url',
            field=models.ImageField(blank=True, upload_to='Media/images/movies'),
        ),
    ]
