# Generated by Django 2.2 on 2019-05-09 14:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0002_auto_20190509_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='movie_url',
            field=models.FileField(blank=True, help_text='MP4,MKV,3GP Files allowed', upload_to='Media/movies', validators=[django.core.validators.FileExtensionValidator(['mp4', 'mkv', 'flv'])]),
        ),
    ]
